DROP TABLE IF EXISTS santri CASCADE;
DROP TABLE IF EXISTS orangtua CASCADE;
DROP TABLE IF EXISTS kelas CASCADE;
DROP TABLE IF EXISTS guru CASCADE;
DROP TABLE IF EXISTS mata_pelajaran CASCADE;
DROP TABLE IF EXISTS jabatan CASCADE;

CREATE TABLE IF NOT EXISTS kelas (
  id SERIAL PRIMARY KEY,
  jenis VARCHAR(20) NOT NULL CHECK (jenis IN ('Diniyah', 'Sekolah')),
  nama VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (jenis, nama)
);

CREATE TABLE IF NOT EXISTS orangtua (
  id SERIAL PRIMARY KEY,
  nama_ayah VARCHAR(150),
  nama_ibu VARCHAR(150),
  pekerjaan_ayah VARCHAR(120),
  pekerjaan_ibu VARCHAR(120),
  no_hp_ayah VARCHAR(60),
  no_hp_ibu VARCHAR(60),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS santri (
  id SERIAL PRIMARY KEY,
  nis VARCHAR(50) NOT NULL UNIQUE,
  nik VARCHAR(50),
  nama VARCHAR(150) NOT NULL,
  kelas_diniyah_id INTEGER REFERENCES kelas(id),
  kelas_sekolah_id INTEGER REFERENCES kelas(id),
  tempat_lahir VARCHAR(120),
  tanggal_lahir DATE,
  alamat TEXT,
  orangtua_id INTEGER REFERENCES orangtua(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS mata_pelajaran (
  id SERIAL PRIMARY KEY,
  nama VARCHAR(120) NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS jabatan (
  id SERIAL PRIMARY KEY,
  nama VARCHAR(120) NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS guru (
  id SERIAL PRIMARY KEY,
  nip VARCHAR(50) UNIQUE,
  nama VARCHAR(150) NOT NULL,
  mata_pelajaran_id INTEGER NOT NULL REFERENCES mata_pelajaran(id) ON DELETE RESTRICT,
  jabatan_id INTEGER NOT NULL REFERENCES jabatan(id) ON DELETE RESTRICT,
  no_hp VARCHAR(60) NOT NULL,
  alamat TEXT NOT NULL,
  status VARCHAR(80) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
